# Generated by Django 5.2.8 on 2025-12-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBreadth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('advancing_stocks', models.IntegerField()),
                ('declining_stocks', models.IntegerField()),
                ('unchanged_stocks', models.IntegerField()),
                ('total_stocks', models.IntegerField()),
                ('advance_decline_line', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Market Breadth Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_marketb_timesta_230c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('news_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_newsdat_timesta_b9c8bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='PnLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('total_pnl', models.DecimalField(decimal_places=2, max_digits=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'P&L Data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_pnldata_timesta_03a17f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SarimaxForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('forecast_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'SARIMAX Forecasts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='api_sarimax_symbol_c353cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Ticks',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='api_stockti_symbol_d52a3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolumeSpike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('spike_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Volume Spikes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='api_volumes_symbol_6fb568_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of shares owned (supports fractional shares)', max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, help_text='Average purchase price per share', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['portfolio', 'symbol'], name='api_stock_portfol_f9ebd9_idx'), models.Index(fields=['symbol'], name='api_stock_symbol_30d1a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'symbol'), name='unique_portfolio_symbol')],
            },
        ),
    ]
