# Generated by Django 5.2.8 on 2025-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktick',
            name='symbol',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
