# Generated by Django 5.2.8 on 2025-12-03 18:25

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Portfolio', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of shares owned (supports fractional shares)', max_digits=15)),
                ('cost_basis', models.DecimalField(decimal_places=2, help_text='Average purchase price per share', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
                'indexes': [
                    models.Index(fields=['portfolio', 'symbol'], name='api_stock_portfol_idx'),
                    models.Index(fields=['symbol'], name='api_stock_symbol_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('portfolio', 'symbol'), name='unique_portfolio_symbol'),
        ),
    ]
