# Generated by Django 5.2.8 on 2025-12-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_portfolio_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEWS', 'News Alert'), ('VOLUME_SPIKE', 'Volume Spike Alert')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('ARCHIVED', 'Archived')], db_index=True, default='UNREAD', max_length=10)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_alerts_enabled', models.BooleanField(default=True)),
                ('volume_spike_alerts_enabled', models.BooleanField(default=True)),
                ('min_volume_spike_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum volume spike percentage to trigger notification (e.g., 50.0 for 50%)', max_digits=5)),
                ('web_notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='api_stock_portfol_f9ebd9_idx',
            old_name='api_stock_portfol_idx',
        ),
        migrations.RenameIndex(
            model_name='stock',
            new_name='api_stock_symbol_30d1a9_idx',
            old_name='api_stock_symbol_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='api_notific_user_id_48bbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='api_notific_user_id_a234fa_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['symbol', '-timestamp'], name='api_notific_symbol_8c452a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', 'status'], name='api_notific_user_id_686b3c_idx'),
        ),
    ]
