# Generated by Django 5.2.8 on 2025-12-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_stocktick_symbol'),
        ('api', '0003_notification_notificationpreference_and_more'),
    ]

    operations = [
    ]
