# Generated by Django 5.2.8 on 2025-12-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20251207_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktick',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
