# Generated by Django 5.2.8 on 2025-12-07 09:07

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_chatmessage_agent_name_chatmessage_kafka_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('drawdown', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum acceptable drawdown percentage (e.g., 20.0 for 20%)', max_digits=5)),
                ('beta', models.DecimalField(decimal_places=2, default=1.0, help_text='Portfolio beta relative to market (e.g., 1.0 for market neutral)', max_digits=4)),
                ('hurdle_rate', models.DecimalField(decimal_places=2, default=8.0, help_text='Minimum acceptable return rate percentage (e.g., 8.0 for 8%)', max_digits=5)),
                ('sector_exposure_limits', models.JSONField(default=users.models.get_default_sector_limits, help_text='Maximum exposure percentage per sector')),
                ('whitelist', models.JSONField(default=users.models.get_default_whitelist, help_text='Allowed domains for news and data sources')),
                ('blacklist', models.JSONField(default=users.models.get_default_blacklist, help_text='Blocked domains for news and data sources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
